name: Evin Ugur
markdown: redcarpet
pygments: true
description: The blog of a CS enthusiast - Evin Ugur
fb: 1578666879
ogtype: website
mailme: <a href="mailto:evinoog96@gmail.com">evinoog96@gmail.com</a>
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-40703482-3'