name: Evin Ugur
exclude: ['README.md']
markdown: redcarpet
pygments: true.
description: The blog of a CS enthusiast - Evin Ugur
fb: 1578666879
ogtype: website
mailme: <a href="mailto:evinoog96@gmail.com">evinoog96@gmail.com</a>
resumeLink: https://docs.google.com/document/d/13lEzyUu9JkQEUNfL_vkJDKRV_7oAFxbYTSAL28uRnoU/